[workspace]
authors = ["Sydney <1607170145@qq.com>"]
channels = ["conda-forge"]
name = "非线性系统"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.13.9"


[pypi-dependencies]
matplotlib = ">=3.10.8, <4"
numpy = ">=2.3.5, <3"
pandas = ">=2.3.3, <3"
streamlit = ">=1.52.1, <2"

